// Built-in channels. Bumping PRESET_VERSION makes the server add new presets
// to an existing state.json without touching the user's own channels.
export const PRESET_VERSION = 9;

const ch = (group, id, name, include, minScore, exclude = []) => ({ id, name, include, exclude, minScore, group });

export const RAW_PRESETS = [
  ch('Destaques', 'top', 'Os melhores', [], 400),
  ch('Destaques', 'genga', 'Genga e bastidores', ['genga'], 50),
  ch('Destaques', 'genga-cmp', 'Genga lado a lado', ['genga_comparison'], 0),

  ch('Estilos', 'efeitos', 'Efeitos', ['effects'], 300, ['western']),
  ch('Estilos', 'lutas', 'Lutas', ['fighting'], 300),
  ch('Estilos', 'explosoes', 'Explosões', ['explosions'], 200),
  ch('Estilos', 'fogo', 'Fogo', ['fire'], 200),
  ch('Estilos', 'fumaca', 'Fumaça', ['smoke'], 300),
  ch('Estilos', 'liquidos', 'Líquidos', ['liquid'], 200),
  ch('Estilos', 'destrocos', 'Destroços', ['debris'], 300),
  ch('Estilos', 'raios', 'Raios', ['lightning'], 150),
  ch('Estilos', 'feixes', 'Feixes de energia', ['beams'], 150),
  ch('Estilos', 'impacto', 'Impact frames', ['impact_frames'], 200),
  ch('Estilos', 'smears', 'Smears', ['smears'], 300),
  ch('Estilos', 'itano', 'Itano circus', ['itano_circus'], 50),
  ch('Estilos', 'mecha', 'Mecha', ['mecha'], 150),
  ch('Estilos', 'criaturas', 'Criaturas', ['creatures'], 200),
  ch('Estilos', 'cabelo', 'Cabelo e tecido', ['hair', 'fabric'], 150),
  ch('Estilos', 'corrida', 'Corrida', ['running'], 150),
  ch('Estilos', 'atuacao', 'Atuação de personagem', ['character_acting'], 300),
  ch('Estilos', 'choro', 'Choro', ['crying'], 50),
  ch('Estilos', 'danca', 'Dança e show', ['dancing'], 50),
  ch('Estilos', 'esporte', 'Esporte', ['sports'], 50),
  ch('Estilos', 'comida', 'Comida', ['food'], 30),
  ch('Estilos', 'cenario', 'Cenário animado', ['background_animation'], 200),
  ch('Estilos', 'rotacao', 'Rotação desenhada', ['rotation'], 100),
  ch('Estilos', 'henshin', 'Transformação', ['henshin'], 30),
  ch('Estilos', 'morphing', 'Morphing', ['morphing'], 100),
  ch('Animadores', 'kanada', 'Yoshinori Kanada', ['yoshinori_kanada'], 0),

  ch('Animadores', 'yutapon', 'Yutaka Nakamura', ['yutaka_nakamura'], 100),
  ch('Animadores', 'matsumoto', 'Norio Matsumoto', ['norio_matsumoto'], 50),
  ch('Animadores', 'iso', 'Mitsuo Iso', ['mitsuo_iso'], 30),
  ch('Animadores', 'ohira', 'Shinya Ohira', ['shinya_ohira'], 30),
  ch('Animadores', 'inoue', 'Toshiyuki Inoue', ['toshiyuki_inoue'], 30),
  ch('Animadores', 'yoshinari', 'Yoh Yoshinari', ['yoh_yoshinari'], 30),
  ch('Animadores', 'imaishi', 'Hiroyuki Imaishi', ['hiroyuki_imaishi'], 30),
  ch('Animadores', 'kameda', 'Yoshimichi Kameda', ['yoshimichi_kameda'], 30),
  ch('Animadores', 'bahi', 'Bahi JD', ['bahi_jd'], 30),
  ch('Animadores', 'hayashi', 'Yuki Hayashi', ['yuki_hayashi'], 50),
  ch('Animadores', 'hashimoto', 'Takashi Hashimoto', ['takashi_hashimoto'], 50),
  ch('Animadores', 'iwane', 'Masaaki Iwane', ['masaaki_iwane'], 30),
  ch('Animadores', 'miyazaki', 'Hayao Miyazaki', ['hayao_miyazaki'], 30),

  ch('Animes', 'mob', 'Mob Psycho 100', ['mob'], 100), // o site esconde o nome da série; 'mob' é a tag que junta tudo,
  ch('Animes', 'jjk', 'Jujutsu Kaisen', ['jujutsu_kaisen_series'], 100),
  ch('Animes', 'csm', 'Chainsaw Man', ['chainsaw_man_series'], 50),
  ch('Animes', 'frieren', 'Frieren', ['sousou_no_frieren_series'], 50),
  ch('Animes', 'dandadan', 'Dandadan', ['dandadan'], 50),
  ch('Animes', 'kny', 'Demon Slayer', ['kimetsu_no_yaiba_series'], 50),
  ch('Animes', 'mha', 'My Hero Academia', ['my_hero_academia_series'], 100),
  ch('Animes', 'firef', 'Fire Force', ['fire_force_series'], 50),
  ch('Animes', 'jojo', 'JoJo', ["jojo's_bizarre_adventure_series"], 30),
  ch('Animes', 'naruto', 'Naruto', ['naruto'], 100),
  ch('Animes', 'dbz', 'Dragon Ball', ['dragon_ball_series'], 50),
  ch('Animes', 'eva', 'Evangelion', ['neon_genesis_evangelion_series'], 50),
  ch('Animes', 'aot', 'Attack on Titan', ['shingeki_no_kyojin_series'], 50),
  ch('Animes', 'gundam', 'Gundam', ['gundam'], 50),
  ch('Animes', 'precure', 'Precure', ['precure'], 50),
  ch('Animes', 'kll', 'Kill la Kill', ['kill_la_kill'], 30),
  ch('Animes', 'kkk', 'Kekkai Sensen', ['kekkai_sensen_series'], 50),


  ch('Assinaturas', 'ass-flare', 'Kanada light flare', ['kanada_light_flare'], 50),
  ch('Assinaturas', 'ass-kutsuna', 'Raio do Kutsuna', ['kutsuna_lightning'], 30),
  ch('Assinaturas', 'ass-wakame', 'Sombra wakame', ['wakame_shadows'], 30),
  ch('Assinaturas', 'ass-umakoshi', 'Olho do Umakoshi', ['umakoshi_eye'], 0),
  ch('Assinaturas', 'ass-cubes', 'Cubos do Yutapon', ['yutapon_cubes'], 30),
  ch('Assinaturas', 'ass-dragon', 'Dragão do Kanada', ['kanada_dragon'], 0),
  ch('Assinaturas', 'ass-obari', 'Soco do Obari', ['obari_punch'], 0),
  ch('Assinaturas', 'ass-ebata', 'Andar do Ebata', ['ebata_walk'], 0),
  ch('Cenas', 'cena-walk', 'Ciclo de caminhada', ['walk_cycle'], 50),
  ch('Cenas', 'cena-crowd', 'Multidão', ['crowd'], 50),
  ch('Cenas', 'cena-vehicle', 'Veículos', ['vehicle'], 150),
  ch('Cenas', 'cena-animals', 'Animais', ['animals'], 150),
  ch('Cenas', 'cena-flying', 'Voo', ['flying'], 100),
  ch('Cenas', 'cena-falling', 'Queda', ['falling'], 100),
  ch('Cenas', 'cena-ice', 'Gelo', ['ice'], 50),
  ch('Cenas', 'cena-wind', 'Vento', ['wind'], 200),
  ch('Cenas', 'cena-sparks', 'Faíscas', ['sparks'], 200),
  ch('Cenas', 'cena-instr', 'Instrumentos', ['instruments'], 20),
  ch('Cenas', 'cena-op', 'Aberturas e títulos', ['title_animation'], 20),
  ch('Cenas', 'cena-roto', 'Rotoscopia', ['rotoscope'], 20),
  ch('Cenas', 'cena-pb', 'Preto e branco', ['black_and_white'], 30),
  ch('Cenas', 'cena-stop', 'Stop motion', ['stop_motion'], 0),
  ch('Cenas', 'cena-3dbg', 'Cenário 3D', ['3d_background'], 50),
  ch('Cenas', 'cena-web', 'Webgen', ['web'], 100),
  ch('Cenas', 'cena-gattai', 'Combinação de robô', ['gattai'], 0),
  ch('Cenas', 'cena-henkei', 'Transformação de robô', ['henkei'], 0),
  ch('Bastidores', 'bst-story', 'Storyboard', ['storyboard'], 0),
  ch('Bastidores', 'bst-layout', 'Layout', ['layout'], 20),
  ch('Bastidores', 'bst-rough', 'Rascunho', ['rough'], 0),
  ch('Bastidores', 'bst-douga', 'Douga', ['douga'], 0),
  ch('Ocidental', 'oc-western', 'Ocidental', ['western'], 200),
  ch('Ocidental', 'oc-kahl', 'Milt Kahl', ['milt_kahl'], 0),
  ch('Ocidental', 'oc-thomas', 'Frank Thomas', ['frank_thomas'], 0),
  ch('Ocidental', 'oc-johnston', 'Ollie Johnston', ['ollie_johnston'], 0),
  ch('Ocidental', 'oc-larson', 'Eric Larson', ['eric_larson'], 0),
  ch('Ocidental', 'oc-natwick', 'Grim Natwick', ['grim_natwick'], 0),
  ch('Ocidental', 'oc-castle', 'Castlevania', ['castlevania_series'], 50),
  ch('Ocidental', 'oc-arcane', 'Arcane', ['arcane'], 0),
  ch('Ocidental', 'oc-spider', 'Aranhaverso', ['spider-man'], 30),
  ch('Ocidental', 'oc-chansard', 'Vincent Chansard', ['vincent_chansard'], 0),
  ch('Clipes musicais', 'mv-eve', 'Eve', ['eve_music_videos'], 0),
  ch('Clipes musicais', 'mv-zutomayo', 'ZUTOMAYO', ['zutomayo_music_videos'], 0),
  ch('Clipes musicais', 'mv-yoasobi', 'YOASOBI', ['yoasobi_music_videos'], 0),
  ch('Animadores', 'a-tanaka', 'Hironori Tanaka', ['hironori_tanaka'], 0),
  ch('Animadores', 'a-sato', 'Toshiyuki Sato', ['toshiyuki_sato'], 0),
  ch('Animadores', 'a-shida', 'Naotoshi Shida', ['naotoshi_shida'], 0),
  ch('Animadores', 'a-ryotanaka', 'Ryo Tanaka', ['ryo_tanaka'], 0),
  ch('Animadores', 'a-okubo', 'Masao Okubo', ['masao_okubo'], 0),
  ch('Animadores', 'a-abe', 'Nozomu Abe', ['nozomu_abe'], 0),
  ch('Animadores', 'a-takeuchi', 'Tetsuya Takeuchi', ['tetsuya_takeuchi'], 0),
  ch('Animadores', 'a-yoshihara', 'Tatsuya Yoshihara', ['tatsuya_yoshihara'], 0),
  ch('Animadores', 'a-honda', 'Takeshi Honda', ['takeshi_honda'], 0),
  ch('Animadores', 'a-kanno', 'Yoshihiro Kanno', ['yoshihiro_kanno'], 0),
  ch('Animadores', 'a-kou', 'Kou Yoshinari', ['kou_yoshinari'], 0),
  ch('Animadores', 'a-sushio', 'Sushio', ['sushio'], 0),
  ch('Animadores', 'a-kakita', 'Hideki Kakita', ['hideki_kakita'], 0),
  ch('Animadores', 'a-obari', 'Masami Obari', ['masami_obari'], 0),
  ch('Animadores', 'a-kozuma', 'Shinsaku Kozuma', ['shinsaku_kozuma'], 0),
  ch('Animadores', 'a-amemiya', 'Akira Amemiya', ['akira_amemiya'], 0),
  ch('Animadores', 'a-imai', 'Arifumi Imai', ['arifumi_imai'], 0),
  ch('Animadores', 'a-oshiyama', 'Kiyotaka Oshiyama', ['kiyotaka_oshiyama'], 0),
  ch('Animadores', 'a-okiura', 'Hiroyuki Okiura', ['hiroyuki_okiura'], 0),
  ch('Animadores', 'a-kondo', 'Yoshifumi Kondo', ['yoshifumi_kondo'], 0),
  ch('Animadores', 'a-park', 'Sunghoo Park', ['sunghoo_park'], 0),
  ch('Animadores', 'a-tu', 'Yong-ce Tu', ['yong-ce_tu'], 0),
  ch('Animadores', 'a-kise', 'Kazuchika Kise', ['kazuchika_kise'], 0),
  ch('Animadores', 'a-umetsu', 'Yasuomi Umetsu', ['yasuomi_umetsu'], 0),
  ch('Animadores', 'a-kiso', 'Yuuta Kiso', ['yuuta_kiso'], 0),
  ch('Animadores', 'a-takase', 'Kenichi Takase', ['kenichi_takase'], 0),
  ch('Animes', 'pokemon', 'Pokémon', ['pokemon'], 100),
  ch('Animes', 'fate', 'Fate', ['fate_series'], 50),
  ch('Animes', 'bleach', 'Bleach', ['bleach_series'], 50),
  ch('Animes', 'lupin', 'Lupin III', ['lupin_iii'], 30),
  ch('Animes', 'imas', 'Idolmaster', ['the_idolmaster_series'], 20),
  ch('Animes', 'digimon', 'Digimon', ['digimon'], 20),
  ch('Animes', 'fma', 'Fullmetal Alchemist', ['fullmetal_alchemist'], 30),
  ch('Animes', 'yugioh', 'Yu-Gi-Oh!', ['yu-gi-oh!'], 20),
  ch('Animes', 'gintama', 'Gintama', ['gintama'], 20),
  ch('Animes', 'blackclover', 'Black Clover', ['black_clover'], 50),
  ch('Animes', 'sailormoon', 'Sailor Moon', ['bishoujo_senshi_sailor_moon'], 20),
  ch('Animes', 'nanoha', 'Nanoha', ['mahou_shoujo_lyrical_nanoha'], 20),
  ch('Animes', 'symphogear', 'Symphogear', ['senki_zesshou_symphogear_series'], 20),
  ch('Animes', 'sao', 'Sword Art Online', ['sword_art_online_series'], 50),
  ch('Animes', 'gits', 'Ghost in the Shell', ['ghost_in_the_shell_series'], 20),
  ch('Animes', 'ranma', 'Ranma 1/2', ['ranma_1/2'], 20),
  ch('Animes', 'urusei', 'Urusei Yatsura', ['urusei_yatsura_series'], 20),
  ch('Animes', 'toaru', 'Index e Railgun', ['to_aru_series'], 30),
  ch('Animes', 'eureka', 'Eureka Seven', ['eureka_seven_series'], 20),
  ch('Animes', 'haikyuu', 'Haikyuu!!', ['haikyuu!!_series'], 30),
  ch('Animes', 'ttgl', 'Gurren Lagann', ['tengen_toppa_gurren_lagann_series'], 50),
  ch('Animes', 'macross', 'Macross', ['macross_saga'], 20),
  ch('Animes', 'monogatari', 'Monogatari', ['monogatari_series'], 20),
  ch('Animes', 'madoka', 'Madoka Magica', ['mahou_shoujo_madoka_magica_series'], 30),
  ch('Animes', 'lovelive', 'Love Live!', ['love_live!_series'], 20),
  ch('Animes', 'eupho', 'Hibike! Euphonium', ['hibike!_euphonium_series'], 20),
  ch('Animes', 'ranking', 'Ousama Ranking', ['ousama_ranking_series'], 30),
  ch('Animes', 'geass', 'Code Geass', ['code_geass'], 20),
  ch('Animes', 'umamusume', 'Uma Musume', ['uma_musume_series'], 30),
  ch('Animes', 'sololeveling', 'Solo Leveling', ['solo_leveling'], 50),
  ch('Animes', 'kon', 'K-On!', ['k-on_series'], 20),
  ch('Animes', 'yyh', 'Yu Yu Hakusho', ['yu_yu_hakusho'], 20),
  ch('Animes', 'inuyasha', 'Inuyasha', ['inuyasha'], 20),
  ch('Animes', 'dunmeshi', 'Dungeon Meshi', ['dungeon_meshi'], 30),
  ch('Animes', 'lwa', 'Little Witch Academia', ['little_witch_academia'], 30),
  ch('Animes', 'flcl', 'FLCL', ['flcl_series'], 30),
  ch('Animes', 'cyborg009', 'Cyborg 009', ['cyborg_009'], 10),
  ch('Animes', 'dandy', 'Space Dandy', ['space_dandy'], 30),
  ch('Animes', 'seiya', 'Saint Seiya', ['saint_seiya_series'], 20),
  ch('Animes', 'mushoku', 'Mushoku Tensei', ['mushoku_tensei_series'], 30),
  ch('Animes', 'rezero', 'Re:Zero', ['re:_zero_kara_hajimeru_isekai_seikatsu_series'], 30),
  ch('Animes', 'danmachi', 'DanMachi', ['dungeon_ni_deai_o_motomeru_no_wa_machigatte_iru_darouka_series'], 30),
  ch('Animes', 'doraemon', 'Doraemon', ['doraemon'], 20),
  ch('Animes', 'shinchan', 'Crayon Shin-chan', ['crayon_shinchan'], 20),
  ch('Animes', 'conan', 'Detective Conan', ['detective_conan'], 20),
  ch('Animes', 'magi', 'Magi', ['magi_series'], 20),
  ch('Animadores', 'a-imamura', 'Ryo Imamura', ['ryo_imamura'], 0),


  // combos: a style crossed with a group of anime or animators (counts measured on 2026-10-07)
  ch('Combos', 'cx-danca-roupa', 'Dança esvoaçante', ['dancing', 'hair', 'fabric'], 0),
  ch('Combos', 'cx-idols', 'Idols no palco', ['dancing', 'performance', '~love_live!_series', '~the_idolmaster_series', '~hololive', '~uma_musume_series'], 0),
  ch('Combos', 'cx-magical', 'Transformação de garota mágica', ['henshin', '~precure', '~bishoujo_senshi_sailor_moon', '~mahou_shoujo_lyrical_nanoha', '~senki_zesshou_symphogear_series', '~cutey_honey_series'], 0),
  ch('Combos', 'cx-luta-smear', 'Lutas com smears', ['fighting', 'smears'], 300),
  ch('Combos', 'cx-impacto', 'Impacto e destroços', ['impact_frames', 'debris'], 200),
  ch('Combos', 'cx-fogo-exp', 'Fogo e explosão', ['fire', 'explosions'], 200),
  ch('Combos', 'cx-corrida-cabelo', 'Corrida com cabelo ao vento', ['running', 'hair'], 100),
  ch('Combos', 'cx-mecha-feixe', 'Mecha e feixes', ['mecha', 'beams'], 100),
  ch('Combos', 'cx-luta-ar', 'Lutas no ar', ['fighting', 'flying'], 100),
  ch('Combos', 'cx-kanada-exp', 'Kanada e explosões', ['kanada_light_flare', 'explosions'], 0),
  ch('Combos', 'cx-yutapon-luta', 'Yutaka Nakamura lutando', ['yutaka_nakamura', 'fighting'], 0),
  ch('Combos', 'cx-web-luta', 'Webgen na luta', ['web', 'fighting'], 50),
  ch('Combos', 'cx-bichos', 'Bichos correndo', ['animals', 'running'], 50),
  ch('Combos', 'cx-choro', 'Choro dramático', ['crying', 'character_acting'], 50),
  ch('Combos', 'cx-comida', 'Comida com atuação', ['food', 'character_acting'], 30),
  ch('Combos', 'cx-liq-fumaca', 'Líquido, fumaça e efeito', ['liquid', 'smoke', 'effects'], 300),
  ch('Combos', 'cx-pancadaria', 'Pancadaria com poeira', ['fighting', 'debris', 'smoke'], 300),
  ch('Combos', 'cx-obari-luta', 'Obari na porrada', ['masami_obari', 'fighting'], 0),
  ch('Combos', 'cx-vento-cabelo', 'Vento no cabelo', ['hair', 'wind'], 100),
  ch('Combos', 'cx-vento-roupa', 'Roupa ao vento', ['fabric', 'wind'], 100),
  ch('Combos', 'cx-esporte', 'Esporte em disparada', ['sports', 'running'], 30),
  ch('Combos', 'cx-perseguicao', 'Perseguição explosiva', ['vehicle', 'explosions'], 100),
  ch('Combos', 'cx-queda', 'Queda e destroços', ['falling', 'debris'], 50),
];

// optional machine-only channels: presets.local.mjs (not in git)
// exports EXTRA (list of presets), FLAG ({ id: fields to override }) and CATEGORY
let local = { EXTRA: [], FLAG: {} };
try { local = await import('./presets.local.mjs'); } catch {}
// English names for presets that aren't proper nouns (English UI)
export const NAMES_EN = {
  'top': 'The very best',
  'genga': 'Genga and behind the scenes',
  'genga-cmp': 'Genga side by side',
  'efeitos': 'Effects',
  'lutas': 'Fights',
  'explosoes': 'Explosions',
  'fogo': 'Fire',
  'fumaca': 'Smoke',
  'liquidos': 'Liquids',
  'destrocos': 'Debris',
  'raios': 'Lightning',
  'feixes': 'Energy beams',
  'criaturas': 'Creatures',
  'cabelo': 'Hair and fabric',
  'corrida': 'Running',
  'atuacao': 'Character acting',
  'choro': 'Crying',
  'danca': 'Dance and performance',
  'esporte': 'Sports',
  'comida': 'Food',
  'cenario': 'Background animation',
  'rotacao': 'Hand-drawn rotation',
  'henshin': 'Transformation',
  'ass-kutsuna': 'Kutsuna lightning',
  'ass-wakame': 'Wakame shadows',
  'ass-umakoshi': 'Umakoshi eyes',
  'ass-cubes': 'Yutapon cubes',
  'ass-dragon': 'Kanada dragon',
  'ass-obari': 'Obari punch',
  'ass-ebata': 'Ebata walk',
  'cena-walk': 'Walk cycles',
  'cena-crowd': 'Crowds',
  'cena-vehicle': 'Vehicles',
  'cena-animals': 'Animals',
  'cena-flying': 'Flight',
  'cena-falling': 'Falling',
  'cena-ice': 'Ice',
  'cena-wind': 'Wind',
  'cena-sparks': 'Sparks',
  'cena-instr': 'Instruments',
  'cena-op': 'Openings and titles',
  'cena-roto': 'Rotoscoping',
  'cena-pb': 'Black and white',
  'cena-3dbg': '3D backgrounds',
  'cena-gattai': 'Robot combining',
  'cena-henkei': 'Robot transformation',
  'bst-rough': 'Roughs',
  'oc-western': 'Western',
  'oc-spider': 'Spider-Verse',
  'toaru': 'Index and Railgun',
  'cx-danca-roupa': 'Flowing dance',
  'cx-idols': 'Idols on stage',
  'cx-magical': 'Magical girl transformation',
  'cx-luta-smear': 'Fights with smears',
  'cx-impacto': 'Impact and debris',
  'cx-fogo-exp': 'Fire and explosions',
  'cx-corrida-cabelo': 'Running with hair in the wind',
  'cx-mecha-feixe': 'Mecha and beams',
  'cx-luta-ar': 'Aerial fights',
  'cx-kanada-exp': 'Kanada and explosions',
  'cx-yutapon-luta': 'Yutaka Nakamura fights',
  'cx-web-luta': 'Webgen fights',
  'cx-bichos': 'Animals running',
  'cx-choro': 'Dramatic crying',
  'cx-comida': 'Food acting',
  'cx-liq-fumaca': 'Liquid, smoke and effects',
  'cx-pancadaria': 'Brawls and dust',
  'cx-obari-luta': 'Obari brawls',
  'cx-vento-cabelo': 'Hair in the wind',
  'cx-vento-roupa': 'Clothes in the wind',
  'cx-esporte': 'Sports sprint',
  'cx-perseguicao': 'Explosive chases',
  'cx-queda': 'Falling and debris',
};

export const EXTRA_CATEGORY = local.CATEGORY || null;
export const ALL_PRESETS = [...RAW_PRESETS, ...(local.EXTRA || [])].map((p) => ({ ...p, ...((local.FLAG || {})[p.id] || {}) }));

// minScore and posts measured by scripts/medir-presets.mjs: the minimum score drops until the
// channel has enough clips, and the guide sorts each group by post count
import fs from 'node:fs';
const readJson = (f) => { try { return JSON.parse(fs.readFileSync(new URL(f, import.meta.url), 'utf8')); } catch { return {}; } };
const stats = { ...readJson('./preset-stats.local.json'), ...readJson('./preset-stats.json') };
export const PRESETS = ALL_PRESETS.map((p) => ({ ...p, ...(stats[p.id] || {}), ...(NAMES_EN[p.id] ? { name_en: NAMES_EN[p.id] } : {}) }));
